version: "3.1"
volumes:
  scout-local-database-data:
    driver: local
  grail-local-database-data:
    driver: local
services:
    mongo:
      image: mongo:latest
      container_name: ChestDev
      hostname: chest-dev
      volumes:
        - scout-local-database-data:/data
      ports:
        - "27016:27017"
    webserver:
      image: nginx:alpine
      container_name: ServerDev
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "9202:80"
    application:
      build: docker
      container_name: ScoutDev
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
      environment:
        - PHP_IDE_CONFIG=serverName=APP
      env_file:
        - ./.env
      expose:
        - 9000
    grail:
      image: postgres:latest
      container_name: GrailDev
      hostname: grail-dev
      env_file:
        - ./.env
      environment:
        POSTGRES_USER: "${DB_GRAIL_USER}"
        POSTGRES_DB: "${DB_GRAIL_DATABASE}"
        POSTGRES_PASSWORD: "${DB_GRAIL_PASSWORD}"
      volumes:
        - grail-local-database-data:/var/lib/postgresql/data
      ports:
      - "5433:5432"
