version: "3.1"
volumes:
  scout-database-data:
    driver: local
services:
    webserver:
      image: nginx:alpine
      container_name: scout-server
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "80:80"
    mongo:
      image: mongo:latest
      container_name: scout-database
      volumes:
        - scout-database-data:/data
      ports:
        - 27016:27017
    php-fpm:
      build: docker/php-fpm
      container_name: scout-app
      working_dir: /application
      volumes:
        - .:/application
        - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/8.0/fpm/conf.d/99-overrides.ini
      environment:
        - PHP_IDE_CONFIG=serverName=APP

